# Generated by Django 5.2.10 on 2026-04-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.CharField(blank=True, max_length=200)),
                ('fichier', models.FileField(upload_to='ordonnances/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='clients.client')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'db_table': 'ordonnances',
                'ordering': ['-created_at'],
            },
        ),
    ]
