# Generated by Django 5.2.10 on 2026-04-16 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('numero_lot', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'lignes_achat',
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Achat',
                'db_table': 'achats',
                'ordering': ['-date_commande'],
            },
        ),
    ]
